### ISSUE TITLE
Tiktok will not work with this extension enabled

### ISSUE THREAD

**Issue by Dislocat** [zWolfrost/Better-Volume-Booster#10]
This extension is by far the best volume booster available on Firefox, but annoyingly it seems to break TikTok as it works again as soon as I disable the extension, and sadly there's no way to blacklist the extension so that it doesn't work when TikTok is open.

The error I get is "We're having trouble playing this video. Please refresh and try again."

Hopefully you can find a fix

**Comment by zWolfrost** [comment]
Hi, can you try setting "Send cookies in media requests" in the extension preferences to "Ask" and then going to the TikTok website, opening the extension there and check the "Send cookies" button?

**Comment by Dislocat** [comment]
That fixed it!

Awesome man thank you so much for this and for the extension in general!

Thanks

On Thu, 12 Dec 2024 at 00:10, Luca Russo 'notifications at github.com'
<github+reply+A2VESFPOCX3EXRZ6A6DCKOOFMYFNREVBNHHKF5PN4M=
