### ISSUE TITLE
TikTok videos stop playing

### ISSUE THREAD

**Issue by ozsum** [zWolfrost/Better-Volume-Booster#11]
Hi! 

Just installed this add-on and it's working great except on TikTok. 

I seem to be getting"We're having trouble playing this video. Please try refresh and try again." when trying to play any video. When I uninstall this addon, videos start playing again.

Hope that helps! And thanks.

**Comment by zWolfrost** [comment]
Duplicate of #10. Try the steps there and let me know if they works for you.

**Comment by ozsum** [comment]
> Duplicate of #10. Try the steps there and let me know if they works for you.

That works! Should've checked closed issues first. Thanks!
