### ISSUE TITLE
Bug: Does not work on tiktok videos something went wrong

### ISSUE THREAD

**Issue by molitar** [zWolfrost/Better-Volume-Booster#14]
It will not work on tiktok videos at all says something went wrong try to refresh page. The problem is that it detects no video so I can't even exclude tiktok from Better Volume Booster meaning the extension is useless right now as I can't keep it enabled. Can we please either have a quick toggle for enabling or an easier method to exclude?

**Comment by zWolfrost** [comment]
Hi, do the steps [here (issue #10)](https://github.com/zWolfrost/Better-Volume-Booster/issues/10) fix your problem?

**Comment by molitar** [comment]
Thanks that took care of the problem you may want to change that to be the default value.

**Comment by molitar** [comment]
Thanks that took care of the problem you may want to change that to be the default value.
