### ISSUE TITLE
Possible to support accuradio.com?

### ISSUE THREAD

**Issue by Gitoffthelawn** [zWolfrost/Better-Volume-Booster#2]
Is there any chance the extension could support https://www.accuradio.com ?

I'm guessing not, but never hurts to ask. ❤️

**Comment by zWolfrost** [comment]
Hi, i'm afraid accuradio is already supported, or at least it works for me. Do you have the latest update or are you still on v1.6.0?

**Comment by Gitoffthelawn** [comment]
I'm still using v1.6.0 (due to #1).

**Comment by zWolfrost** [comment]
If you go on the website and search in the inspector the "audio" keyword, you will find the element that is playing the audio. You can see it's source and enable the permission for its website. The extension will most likely work after that

**Comment by Gitoffthelawn** [comment]
Thanks.  Easy enough.  Will do.
