### ISSUE TITLE
I dont get it

### ISSUE THREAD

**Issue by b5white** [zWolfrost/Better-Volume-Booster#9]
How does this work? I don't see any icon or volume button. Says it's installed but I don't see any change.
Suggestion: There should be some instruction about how to use the extension in the description.

**Comment by zWolfrost** [comment]
I think [the screenshots on the add-on page](https://addons.mozilla.org/en-US/firefox/addon/better-volume-booster/) do a well-enough job of explaining how to use the extension. If you can't see the extension button near the URL bar you should probably pin it (Click on the "Extensions" button that looks like a puzzle piece, right click the extension and then tick "Pin to Toolbar")

**Comment by b5white** [comment]
That worked. Thanks.
I think I was confused because my similar Chrome extension auto-pinned the icon.
